        </section>
        <footer>
            <div class="content">
                <div class="container">
                    <div class="row">
                        <div class="col-md-9">
                            <img src="../../imgs/gs.jpg" width="29" height="28" alt="GS" /> &nbsp;&copy; <b>GRUPO SOSOARES</b> Todos os Direitos Reservados
                        </div>
                        <div class="col-md-3">
                            <img src="../../imgs/euro2000.jpg" width="165" height="43" alt="Sistemas Euro2000" title="Sistemas Euro2000">
                            <img src="../../imgs/critec.jpg" width="70" height="23" alt="Critec.pt" title="Critec.pt">
                        </div>
                    </div>
                    <div class="row">
                        <div id="contacts">
                            <div class="col-md-1">
                                <img src="../../imgs/35anos.jpg" width="68" height="77" alt="35 Anos">
                            </div>
                            <div class="col-md-3">
                                <p><b>RUA DO CAMPO ALEGRE, 474</p>
                                <p>4150-170 PORTO - PORTUGAL</b></p>
                            </div>
                            <div class="col-md-2">
                                <p>Tel +351 <b>226 096 709</b></p>
                                <p> Tel +351 <b>226 005 642</b></p>
                            </div>
                            <div class="col-md-3">
                                <p>geral@sosoares.pt</p>
                                <p>comercial@sosoares.pt</p>
                            </div>
                            <div class="col-md-3">
                                &nbsp;
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        <script src="../../js/bootstrap.min.js"></script>
        <script src="../../js/docs.min.js"></script>
    </body>
</html>